# Generated by Django 4.2.16 on 2024-12-05 01:06

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0003_alter_producto_f_fabricacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='f_fabricacion',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.datetime(2015, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))]),
        ),
    ]
