# Generated by Django 4.2.16 on 2024-10-22 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='valoración',
            new_name='valoracion',
        ),
    ]
