# Generated by Django 5.1.3 on 2024-11-07 00:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(choices=[('FIAT', 'FIAT'), ('TOYOTA', 'TOYOTA'), ('FORD', 'FORD'), ('CHEVROLET', 'CHEVROLET')], default='Ford', max_length=20)),
                ('modelo', models.TextField(max_length=100)),
                ('serial_carroceria', models.TextField(max_length=50)),
                ('serial_motor', models.TextField(max_length=50)),
                ('categoria', models.CharField(choices=[('TRANSPORTE', 'TRANSPORTE'), ('PARTICULAR', 'PARTICULAR'), ('CARGA', 'CARGA')], default='Particular', max_length=20)),
                ('precio', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime(2024, 11, 6, 21, 32, 32, 604476))),
                ('fecha_modificacion', models.DateTimeField(default=datetime.datetime(2024, 11, 6, 21, 32, 32, 604476))),
            ],
        ),
    ]
