# Generated by Django 4.2.16 on 2024-11-07 23:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'permissions': [('vehiculo.view', 'Puede ver los vehiculos'), ('development', 'Permiso como Desarrollador'), ('scrum_master', 'Permiso como Scrum Master'), ('product_owner', 'Permiso como Product Owner')]},
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='categoria',
            field=models.CharField(choices=[('PARTICULAR', 'PARTICULAR'), ('TRANSPORTE', 'TRANSPORTE'), ('CARGA', 'CARGA')], default='Particular', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 7, 20, 42, 30, 160622)),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='fecha_modificacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 7, 20, 42, 30, 160622)),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(choices=[('FIAT', 'FIAT'), ('FORD', 'FORD'), ('TOYOTA', 'TOYOTA'), ('CHEVROLET', 'CHEVROLET')], default='Ford', max_length=20),
        ),
    ]
